title: Portafolio de Jessica Ochoa
#logo: /assets/foto-perfil.jpg 
logo: (/assets/images/foto-perfil.jpg){: style="border-radius: 50%; height: 120px;" }
description: QA Tester | Automatización | Pruebas API | Mobile QA
theme: jekyll-theme-minimal
